# Generated by Django 5.1.7 on 2025-04-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employerProfile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School Diploma"),
                            ("associate", "Associate's Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("mba", "MBA"),
                            ("phd", "PhD"),
                            ("diploma", "Diploma"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("responsibilities", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("salary_range", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to="employerProfile.employerprofile",
                    ),
                ),
            ],
        ),
    ]
