# Generated by Django 5.1.7 on 2025-04-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="joblisting",
            table="joblisting",
        ),
    ]
