# Generated by Django 5.1.7 on 2025-04-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0002_alter_joblisting_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobListing",
        ),
    ]
