# Generated by Django 5.1.7 on 2025-05-20 18:12

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employerProfile", "0005_employerprofile_is_deleted"),
        ("jobListing", "0003_delete_joblisting"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "education_requirements",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry_level", "Entry Level"),
                            ("mid_level", "Mid Level"),
                            ("senior_level", "Senior Level"),
                            ("internship", "Internship"),
                        ],
                        default="entry_level",
                        max_length=20,
                    ),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("on_site", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="on_site",
                        max_length=15,
                    ),
                ),
                ("salary_range", models.CharField(max_length=100)),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        max_length=10,
                    ),
                ),
                ("remote_available", models.BooleanField(default=False)),
                ("openings", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to="employerProfile.employerprofile",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "db_table": "joblisting",
            },
        ),
        migrations.CreateModel(
            name="JobViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="jobListing.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_view_log",
            },
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["created_at"], name="joblisting_created_9615d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobviewlog",
            index=models.Index(
                fields=["viewed_at"], name="job_view_lo_viewed__b0fb26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobviewlog",
            unique_together={("job", "user")},
        ),
    ]
