# Generated by Django 5.1.7 on 2025-05-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("part-time", "Part Time"),
                    ("internship", "Internship"),
                    ("contract", "Contract"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
