# Generated by Django 5.1.7 on 2025-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0005_alter_joblisting_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
