# Generated by Django 5.1.7 on 2025-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0006_alter_joblisting_application_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-Time"),
                    ("part-time", "Part Time"),
                    ("internship", "Internship"),
                    ("contract", "Contract"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("on-site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="on-site",
                max_length=15,
            ),
        ),
    ]
