# Generated by Django 5.1.7 on 2025-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0007_alter_joblisting_job_type_alter_joblisting_work_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry_level", "Entry Level"),
                    ("mid_level", "Mid Level"),
                    ("senior_level", "Senior Level"),
                ],
                default="entry_level",
                max_length=20,
            ),
        ),
    ]
