# Generated by Django 5.1.7 on 2025-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobListing", "0008_alter_joblisting_experience_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry-level", "Entry Level"),
                    ("mid-level", "Mid Level"),
                    ("senior-level", "Senior Level"),
                ],
                default="entry-level",
                max_length=20,
            ),
        ),
    ]
