# Generated by Django 5.1.7 on 2025-04-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0002_alter_jobseekerprofile_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobseekerprofile",
            old_name="contact_number",
            new_name="contact_num",
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
