# Generated by Django 5.1.7 on 2025-04-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobSeekerProfile",
            "0003_rename_contact_number_jobseekerprofile_contact_num_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="education",
            field=models.CharField(
                choices=[
                    ("it", "Information Technology"),
                    ("cs", "Computer Science"),
                    ("arch", "Architecture"),
                    ("mba", "MBA"),
                    ("ca", "Chartered Accountant"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="experience_years",
            field=models.CharField(
                choices=[
                    ("fresher", "Fresher"),
                    ("lt1", "Less than 1 year"),
                    ("1plus", "More than 1 year"),
                ],
                default="fresher",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
