# Generated by Django 5.1.7 on 2025-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0004_jobseekerprofile_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("mumbai", "Mumbai"),
                    ("bangalore", "Bangalore"),
                    ("hyderabad", "Hyderabad"),
                    ("delhi", "Delhi"),
                    ("pune", "Pune"),
                    ("chennai", "Chennai"),
                    ("gurgaon", "Gurgaon"),
                    ("noida", "Noida"),
                    ("ahmedabad", "Ahmedabad"),
                    ("kolkata", "Kolkata"),
                    ("remote", "Remote"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
