# Generated by Django 5.1.7 on 2025-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0005_alter_jobseekerprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
