# Generated by Django 5.1.7 on 2025-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0006_jobseekerprofile_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
