# Generated by Django 5.1.7 on 2025-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0007_jobseekerprofile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(max_length=20),
        ),
    ]
