# Generated by Django 5.1.7 on 2025-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0008_alter_jobseekerprofile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="experience_years",
            field=models.CharField(
                choices=[
                    ("fresher", "Fresher"),
                    ("lt1", "Less than 1 year"),
                    ("1-3", "1-3 years"),
                    ("3-5", "3-5 years"),
                    ("5+", "More than 5 years"),
                ],
                default="fresher",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(
                help_text="Enter one or more cities seperated by commas or slashes",
                max_length=255,
            ),
        ),
    ]
