# Generated by Django 5.1.7 on 2025-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0009_alter_jobseekerprofile_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="education",
            field=models.CharField(
                help_text="Enter your education. Be specific (e.g., Bachelor's Degree in Computer Science, High School, etc.)",
                max_length=255,
            ),
        ),
    ]
