# Generated by Django 5.1.7 on 2025-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0010_alter_jobseekerprofile_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="experience_years",
            field=models.CharField(default="fresher", max_length=100),
        ),
    ]
