# Generated by Django 5.1.7 on 2025-05-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobSeekerProfile", "0011_alter_jobseekerprofile_experience_years"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobseekerprofile",
            options={
                "verbose_name": "Jobseeker Profile",
                "verbose_name_plural": "Jobseeker Profiles",
            },
        ),
    ]
