# Generated by Django 5.1.7 on 2025-05-20 18:12

import jobApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to=jobApplication.models.resume_upload_path,
                        validators=[
                            jobApplication.models.validate_resume_file_extension
                        ],
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "jobapplication",
            },
        ),
    ]
