# Generated by Django 5.1.7 on 2025-05-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobApplication", "0001_initial"),
        ("jobListing", "0004_initial"),
        ("jobSeekerProfile", "0012_alter_jobseekerprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobListing.joblisting"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="jobseekerprofile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="jobSeekerProfile.jobseekerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["status"], name="jobapplicat_status_13fcfc_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applied_at"], name="jobapplicat_applied_a672e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("jobseekerprofile", "job")},
        ),
    ]
