# Generated by Django 5.1.7 on 2025-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerProfile", "0002_alter_employerprofile_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employerprofile",
            name="description",
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="industry_type",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("mumbai", "Mumbai"),
                    ("bangalore", "Bangalore"),
                    ("hyderabad", "Hyderabad"),
                    ("delhi", "Delhi"),
                    ("pune", "Pune"),
                    ("chennai", "Chennai"),
                    ("gurgaon", "Gurgaon"),
                    ("noida", "Noida"),
                    ("ahmedabad", "Ahmedabad"),
                    ("kolkata", "Kolkata"),
                    ("remote", "Remote"),
                    ("other", "Other"),
                ],
                default="Mumbai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
    ]
