# Generated by Django 5.1.7 on 2025-04-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerProfile", "0003_remove_employerprofile_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employerprofile",
            options={
                "verbose_name": "Employer Profile",
                "verbose_name_plural": "Employer Profiles",
            },
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="email",
            field=models.EmailField(default="employer@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("mumbai", "Mumbai"),
                    ("bangalore", "Bangalore"),
                    ("hyderabad", "Hyderabad"),
                    ("delhi", "Delhi"),
                    ("pune", "Pune"),
                    ("chennai", "Chennai"),
                    ("gurgaon", "Gurgaon"),
                    ("noida", "Noida"),
                    ("ahmedabad", "Ahmedabad"),
                    ("kolkata", "Kolkata"),
                    ("remote", "Remote"),
                    ("other", "Other"),
                ],
                default="mumbai",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
