# Generated by Django 5.1.7 on 2025-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerProfile", "0004_alter_employerprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
